/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/nZuFlldB4Ha
 */
import Link from "next/link"

export function LandingPage() {
  return (
    <div className="flex flex-col min-h-screen bg-gray-100 dark:bg-gray-800 transition-all duration-500 ease-in-out">
      <header className="px-4 lg:px-6 h-16 flex items-center bg-purple-300 dark:bg-purple-400 transition-all duration-500 ease-in-out">
        <h1 className="text-2xl font-bold text-gray-900 dark:text-gray-100 font-space-grotesk transition-all duration-500 ease-in-out">
          Rishi Srihari
        </h1>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link
            className="text-sm font-medium hover:underline underline-offset-4 transition-all duration-500 ease-in-out"
            href="#"
          >
            Projects
          </Link>
          <Link
            className="text-sm font-medium hover:underline underline-offset-4 transition-all duration-500 ease-in-out"
            href="#"
          >
            About
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32 transition-all duration-500 ease-in-out">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col justify-center space-y-4">
              <div className="space-y-2">
                <img
                  className="w-48 h-48 rounded-full mx-auto transition-transform duration-500 ease-in-out group-hover:scale-105"
                  height="200"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "200/200",
                    objectFit: "cover",
                  }}
                  width="200"
                />
                <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none font-space-grotesk transition-all duration-500 ease-in-out">
                  Hi, I'm Rishi Srihari
                </h1>
                <p className="max-w-[600px] text-gray-500 md:text-xl dark:text-gray-400 font-space-grotesk transition-all duration-500 ease-in-out">
                  A full-stack developer specializing in building web applications.
                </p>
              </div>
            </div>
          </div>
        </section>
        <section
          className="w-full py-12 md:py-24 lg:py-32 bg-purple-400 dark:bg-purple-400 transition-all duration-500 ease-in-out"
          id="projects"
        >
          <div className="container px-4 md:px-6">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl font-space-grotesk transition-all duration-500 ease-in-out">
              Projects
            </h2>
            <div className="mx-auto grid items-start gap-8 sm:max-w-4xl sm:grid-cols-2 md:gap-12 lg:max-w-5xl lg:grid-cols-3 mt-8">
              <div className="group grid gap-4 transition-all duration-200 transform hover:scale-105">
                <img
                  className="w-full h-48 object-cover transition-transform duration-500 ease-in-out group-hover:scale-105"
                  height="200"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "200/200",
                    objectFit: "cover",
                  }}
                  width="200"
                />
                <h3 className="text-lg font-bold font-space-grotesk transition-all duration-500 ease-in-out">
                  Zot Connect
                </h3>
                <p className="text-gray-500 dark:text-gray-400 font-space-grotesk transition-all duration-500 ease-in-out">
                  A brief description of the project.
                </p>
                <div className="flex gap-4">
                  <Link
                    className="text-sm hover:underline underline-offset-4 font-space-grotesk transition-all duration-500 ease-in-out"
                    href="#"
                  >
                    Visit Site
                  </Link>
                  <Link
                    className="text-sm hover:underline underline-offset-4 font-space-grotesk transition-all duration-500 ease-in-out"
                    href="#"
                  >
                    Github
                  </Link>
                </div>
              </div>
              <div className="group grid gap-4 transition-all duration-200 transform hover:scale-105">
                <img
                  className="w-full h-48 object-cover transition-transform duration-500 ease-in-out group-hover:scale-105"
                  height="200"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "200/200",
                    objectFit: "cover",
                  }}
                  width="200"
                />
                <h3 className="text-lg font-bold font-space-grotesk transition-all duration-500 ease-in-out">
                  Project 2
                </h3>
                <p className="text-gray-500 dark:text-gray-400 font-space-grotesk transition-all duration-500 ease-in-out">
                  A brief description of the project.
                </p>
                <div className="flex gap-4">
                  <Link
                    className="text-sm hover:underline underline-offset-4 font-space-grotesk transition-all duration-500 ease-in-out"
                    href="#"
                  >
                    Visit Site
                  </Link>
                  <Link
                    className="text-sm hover:underline underline-offset-4 font-space-grotesk transition-all duration-500 ease-in-out"
                    href="#"
                  >
                    Github
                  </Link>
                </div>
              </div>
              <div className="group grid gap-4 transition-all duration-200 transform hover:scale-105">
                <img
                  className="w-full h-48 object-cover transition-transform duration-500 ease-in-out group-hover:scale-105"
                  height="200"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "200/200",
                    objectFit: "cover",
                  }}
                  width="200"
                />
                <h3 className="text-lg font-bold font-space-grotesk transition-all duration-500 ease-in-out">
                  Project 3
                </h3>
                <p className="text-gray-500 dark:text-gray-400 font-space-grotesk transition-all duration-500 ease-in-out">
                  A brief description of the project.
                </p>
                <div className="flex gap-4">
                  <Link
                    className="text-sm hover:underline underline-offset-4 font-space-grotesk transition-all duration-500 ease-in-out"
                    href="#"
                  >
                    Visit Site
                  </Link>
                  <Link
                    className="text-sm hover:underline underline-offset-4 font-space-grotesk transition-all duration-500 ease-in-out"
                    href="#"
                  >
                    Github
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 transition-all duration-500 ease-in-out" id="about">
          <div className="container px-4 md:px-6">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl font-space-grotesk transition-all duration-500 ease-in-out">
              About Me
            </h2>
            <div className="flex flex-col gap-4 mt-8">
              <p className="max-w-[600px] text-gray-500 md:text-xl dark:text-gray-400 font-space-grotesk transition-all duration-500 ease-in-out">
                I am a full-stack developer with over 5 years of experience in building web applications. I specialize
                in JavaScript and have professional experience working with React and Node.js.
              </p>
              <p className="max-w-[600px] text-gray-500 md:text-xl dark:text-gray-400 font-space-grotesk transition-all duration-500 ease-in-out">
                I have a passion for learning and sharing my knowledge with others as clearly as possible. If you found
                value in something I have created, please feel free to share, comment, and ask me anything!
              </p>
            </div>
          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t bg-purple-400 dark:bg-purple-400 transition-all duration-500 ease-in-out">
        <p className="text-xs text-gray-500 dark:text-gray-400 font-space-grotesk transition-all duration-500 ease-in-out">
          © 2024 Rishi Srihari. All rights reserved.
        </p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link
            className="text-xs hover:underline underline-offset-4 font-space-grotesk transition-all duration-500 ease-in-out"
            href="#"
          >
            Terms of Service
          </Link>
          <Link
            className="text-xs hover:underline underline-offset-4 font-space-grotesk transition-all duration-500 ease-in-out"
            href="#"
          >
            Privacy
          </Link>
        </nav>
      </footer>
    </div>
  );
}
